Public Class FixtureConstants

    Public Const excludeditem As String = "xunit.dll"
    Public Const testValue As String = "test Value"
    Public Const list_Value1 As String = "value1"
    Public Const list_Key1 As String = "key1"
    Public Const list_Value2 As String = "value2"
    Public Const list_Key2 As String = "key2"
    Public Const Loaded As String = "Loaded"
    Public Const list_Key As String = "key"
    Public Const list_Value As String = "value"
    Public Const list_Keyi As String = "Key-i"
    Public Const list_Valuel As String = "value-l"
    Public Const list_Valuei As String = "value-i"
    Public Const Initial As String = "Initial"
    Public Const list_Keya As String = "keya"
    Public Const list_Valuea As String = "valuea"
    Public Const TestFileComponentTest As String = "TestFileComponent.Test"
    Public Const list_Keyl As String = "Key-l"
    Public Const CastleCore As String = "Castle.Core"
    Public Const DeploymentSpikeTasks As String = "DeploymentSpike.Tasks"
    Public Const MockTaskFullName As String = "DeploymentSpike.Fixture.Mocks.ContainerMockTask"
    Public Const MockTaskFailExecuteFullName As String = "DeploymentSpike.Fixture.Mocks.ContainerMockTaskFailExecute"
    Public Const MockTaskFailValidateFullName As String = "DeploymentSpike.Fixture.Mocks.ContainerMockTaskFailValidate"
    Public Const MockSecondTaskFullName As String = "DeploymentSpike.Fixture.Mocks.ContainerSecondMockTask"
    Public Const MockThirdTaskFullName As String = "DeploymentSpike.Fixture.Mocks.ContainerThirdMockTask"
    Public Const MockNotificationFullName As String = "DeploymentSpike.Fixture.Mocks.ContainerMockNotifications"
    Public Const DeploymentSpikeFixtureDoesNotExist As String = "DeploymentSpike.Fixture.Mocks.DoesNotExist"
    Public Const MultipleLogging As String = "DeploymentSpike.Fixture.MultipleLogging"
    Public Const NoLogging As String = "DeploymentSpike.Fixture.NoLogging"
    Public Const loggerFieldName As String = "_logger"
    Public Const MemoryLogClassName As String = "DeploymentSpike.Fixture.MultipleLogging.MemoryLog"


End Class
