'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DeploymentSpike.Notification.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not find the specifed address file: {0}.
        '''</summary>
        Public Shared ReadOnly Property AddressFileNotFound() As String
            Get
                Return ResourceManager.GetString("AddressFileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed Failure - Notification.
        '''</summary>
        Public Shared ReadOnly Property CompletedFailure() As String
            Get
                Return ResourceManager.GetString("CompletedFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed Success - Notification.
        '''</summary>
        Public Shared ReadOnly Property CompletedSuccess() As String
            Get
                Return ResourceManager.GetString("CompletedSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The email address list file was not specified in the configuration and this is a required field..
        '''</summary>
        Public Shared ReadOnly Property ConfigAddressFileNotSpecified() As String
            Get
                Return ResourceManager.GetString("ConfigAddressFileNotSpecified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Current Step&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property CurrentStep() As String
            Get
                Return ResourceManager.GetString("CurrentStep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Public Shared ReadOnly Property DefaultLabel() As String
            Get
                Return ResourceManager.GetString("DefaultLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;p/&gt;&lt;a href=&quot;http://www.google.com&quot; target =&quot;_blank&quot; title=&quot;Contact Us&quot; style=&quot;color: orange; text-decoration: none;&quot;&gt;Contact Us&lt;/a&gt;&lt;p/&gt;&lt;span class=&quot;mobile_link&quot;&gt;555-555-5555&lt;/span&gt;.
        '''</summary>
        Public Shared ReadOnly Property EmailBodyContactInformation() As String
            Get
                Return ResourceManager.GetString("EmailBodyContactInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt; 
        '''&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        '''	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        '''	&lt;title&gt;Your Message Subject or Title&lt;/title&gt;
        '''	&lt;style type=&quot;text/css&quot;&gt;
        '''		/* Based on The MailChimp Reset INLINE: Yes. */  
        '''		/* Client-specific Styles */
        '''		#outlook a {padding:0;} /* Force Outlook to provid [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property EmailBodyHeaderStyle() As String
            Get
                Return ResourceManager.GetString("EmailBodyHeaderStyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;body&gt;&lt;!-- Wrapper/Container Table: Use a wrapper table to control the width and the background color consistently of your email. Use this approach instead of setting attributes on the body tag. --&gt;&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; border=&quot;0&quot; id=&quot;backgroundTable&quot; style=&quot;margin: 0;font-family:Helvetica Neue, Helvetica, Arial, sans-serif;  font-size: 13px;line-height: 18px;  color: #333333;  background-color: #ffffff;&quot;&gt;&lt;tr&gt;&lt;td valign=&quot;top&quot;&gt;.
        '''</summary>
        Public Shared ReadOnly Property EmailBodyTableContainer() As String
            Get
                Return ResourceManager.GetString("EmailBodyTableContainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;thead &gt;&lt;tr&gt;&lt;th {0}&gt;Completed&lt;/th&gt;&lt;th {0}&gt;Step&lt;/th&gt;&lt;th {0}&gt;Deployment Task&lt;/th&gt;&lt;th {0}&gt;Migration Thread&lt;/th&gt;&lt;th {0}&gt;Servers Impacted&lt;/th&gt;&lt;th {0}&gt;Comments&lt;/th&gt;&lt;th {0}&gt;Dependencies&lt;/th&gt;&lt;th {0}&gt;Start Date&lt;/th&gt;&lt;th {0}&gt;Start Time&lt;/th&gt;&lt;th {0}&gt;End Time&lt;/th&gt;&lt;th {0}&gt;Duration&lt;/th&gt;&lt;th {0}&gt;DPW Owner (s)&lt;/th&gt;&lt;th {0}&gt;DC Support&lt;/th&gt;&lt;/tr&gt;&lt;/thead&gt;&lt;tbody&gt;.
        '''</summary>
        Public Shared ReadOnly Property EmailBodyTaskHeader() As String
            Get
                Return ResourceManager.GetString("EmailBodyTaskHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email host not found..
        '''</summary>
        Public Shared ReadOnly Property EmailHostNotFound() As String
            Get
                Return ResourceManager.GetString("EmailHostNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email port not found..
        '''</summary>
        Public Shared ReadOnly Property EmailPortNotFound() As String
            Get
                Return ResourceManager.GetString("EmailPortNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;table class=&quot;table table-bordered table-striped&quot; style=&quot;width: 100%;margin-bottom: 18px;  border: 1px solid #dddddd;  border-left: 0;  border-collapse: separate;  *border-collapse: collapsed;  -webkit-border-radius: 4px;-moz-border-radius: 4px;  border-radius: 4px; &quot;&gt;.
        '''</summary>
        Public Shared ReadOnly Property EmailTableHeader() As String
            Get
                Return ResourceManager.GetString("EmailTableHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There were not any addresses loaded..
        '''</summary>
        Public Shared ReadOnly Property EmptyAddressList() As String
            Get
                Return ResourceManager.GetString("EmptyAddressList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task failed notification not fired due to configuration..
        '''</summary>
        Public Shared ReadOnly Property FailedNotFired() As String
            Get
                Return ResourceManager.GetString("FailedNotFired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From email address not found..
        '''</summary>
        Public Shared ReadOnly Property FromEmailAddressNotFound() As String
            Get
                Return ResourceManager.GetString("FromEmailAddressNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From email name not found..
        '''</summary>
        Public Shared ReadOnly Property FromEmailNameNotFound() As String
            Get
                Return ResourceManager.GetString("FromEmailNameNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The html file was not found..
        '''</summary>
        Public Shared ReadOnly Property MissingHtmlFile() As String
            Get
                Return ResourceManager.GetString("MissingHtmlFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  .
        '''</summary>
        Public Shared ReadOnly Property Space() As String
            Get
                Return ResourceManager.GetString("Space", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specified file in configuration is found:.
        '''</summary>
        Public Shared ReadOnly Property SpecifiedFileFound() As String
            Get
                Return ResourceManager.GetString("SpecifiedFileFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specified file in configuration is not found:.
        '''</summary>
        Public Shared ReadOnly Property SpecifiedFileNotFound() As String
            Get
                Return ResourceManager.GetString("SpecifiedFileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specified folder in configuration is found:.
        '''</summary>
        Public Shared ReadOnly Property SpecifiedFolderFound() As String
            Get
                Return ResourceManager.GetString("SpecifiedFolderFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specified folder in configuration is not found:.
        '''</summary>
        Public Shared ReadOnly Property SpecifiedFolderNotFound() As String
            Get
                Return ResourceManager.GetString("SpecifiedFolderNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Started - Notification.
        '''</summary>
        Public Shared ReadOnly Property Started() As String
            Get
                Return ResourceManager.GetString("Started", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task started notification not fired due to configuration..
        '''</summary>
        Public Shared ReadOnly Property StartedNotFired() As String
            Get
                Return ResourceManager.GetString("StartedNotFired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Step List&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property StepList() As String
            Get
                Return ResourceManager.GetString("StepList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task success notification not fired due to configuration..
        '''</summary>
        Public Shared ReadOnly Property SuccessNotFired() As String
            Get
                Return ResourceManager.GetString("SuccessNotFired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task:.
        '''</summary>
        Public Shared ReadOnly Property Task() As String
            Get
                Return ResourceManager.GetString("Task", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task: {0} has failed to completed at: {1}.
        '''</summary>
        Public Shared ReadOnly Property TaskCompleteFailure() As String
            Get
                Return ResourceManager.GetString("TaskCompleteFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task: {0} has been sucessfully completed at: {1}.
        '''</summary>
        Public Shared ReadOnly Property TaskCompleteSucccess() As String
            Get
                Return ResourceManager.GetString("TaskCompleteSucccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task: {0} has been started at: {1}.
        '''</summary>
        Public Shared ReadOnly Property TaskStarted() As String
            Get
                Return ResourceManager.GetString("TaskStarted", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
