'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DeploymentSpike.Tasks.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The application pool is being recycled: {0}.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationPoolRecycled() As String
            Get
                Return ResourceManager.GetString("ApplicationPoolRecycled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arguments:.
        '''</summary>
        Friend Shared ReadOnly Property Arguments() As String
            Get
                Return ResourceManager.GetString("Arguments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup of Database..
        '''</summary>
        Friend Shared ReadOnly Property BackupofDatabase() As String
            Get
                Return ResourceManager.GetString("BackupofDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database backup -.
        '''</summary>
        Friend Shared ReadOnly Property DatabaseBackup() As String
            Get
                Return ResourceManager.GetString("DatabaseBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The destination folder count does not equal the source folder count..
        '''</summary>
        Friend Shared ReadOnly Property DestinationSourceCountsDifferent() As String
            Get
                Return ResourceManager.GetString("DestinationSourceCountsDifferent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ending backup.
        '''</summary>
        Friend Shared ReadOnly Property EndingBackup() As String
            Get
                Return ResourceManager.GetString("EndingBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Executing Item:.
        '''</summary>
        Friend Shared ReadOnly Property ExecutingItem() As String
            Get
                Return ResourceManager.GetString("ExecutingItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Halting execution of task after setting were validated due to execution flag..
        '''</summary>
        Friend Shared ReadOnly Property ExecutionFlagDiagnostic() As String
            Get
                Return ResourceManager.GetString("ExecutionFlagDiagnostic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extracting from zip:.
        '''</summary>
        Friend Shared ReadOnly Property ExtractFromZip() As String
            Get
                Return ResourceManager.GetString("ExtractFromZip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extraction of files from zip completed. .
        '''</summary>
        Friend Shared ReadOnly Property ExtractionCompleted() As String
            Get
                Return ResourceManager.GetString("ExtractionCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extraction of files from zip starting. .
        '''</summary>
        Friend Shared ReadOnly Property ExtractionStarted() As String
            Get
                Return ResourceManager.GetString("ExtractionStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File copied from:.
        '''</summary>
        Friend Shared ReadOnly Property FileCopiedFrom() As String
            Get
                Return ResourceManager.GetString("FileCopiedFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Deleted:.
        '''</summary>
        Friend Shared ReadOnly Property FileDeleted() As String
            Get
                Return ResourceManager.GetString("FileDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan of file completed with {0} matches found..
        '''</summary>
        Friend Shared ReadOnly Property FileScanCompletedMatches() As String
            Get
                Return ResourceManager.GetString("FileScanCompletedMatches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan of file completed with no matches found..
        '''</summary>
        Friend Shared ReadOnly Property FileScanCompletedNoMatches() As String
            Get
                Return ResourceManager.GetString("FileScanCompletedNoMatches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searched folder: {0} for files with extension: {1} and did not find any..
        '''</summary>
        Friend Shared ReadOnly Property FilesNotFoundinSpecifiedFolder() As String
            Get
                Return ResourceManager.GetString("FilesNotFoundinSpecifiedFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder created:.
        '''</summary>
        Friend Shared ReadOnly Property FolderCreated() As String
            Get
                Return ResourceManager.GetString("FolderCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder Deleted:.
        '''</summary>
        Friend Shared ReadOnly Property FolderDeleted() As String
            Get
                Return ResourceManager.GetString("FolderDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Match found on line {0} {1}.
        '''</summary>
        Friend Shared ReadOnly Property MatchFound() As String
            Get
                Return ResourceManager.GetString("MatchFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The backup file was not in the settings.  This is a required setting for the task to run..
        '''</summary>
        Friend Shared ReadOnly Property MissingBackupFile() As String
            Get
                Return ResourceManager.GetString("MissingBackupFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The connection string was not in the settings.  This is a required setting for the task to run..
        '''</summary>
        Friend Shared ReadOnly Property MissingConnectionStringSetting() As String
            Get
                Return ResourceManager.GetString("MissingConnectionStringSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The database name was not in the settings.  This is a required setting for the task to run..
        '''</summary>
        Friend Shared ReadOnly Property MissingDatabaseSetting() As String
            Get
                Return ResourceManager.GetString("MissingDatabaseSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The destination folder was not in the settings.  This is a required setting for the task to run..
        '''</summary>
        Friend Shared ReadOnly Property MissingDestinationFolder() As String
            Get
                Return ResourceManager.GetString("MissingDestinationFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The executing arguments entry is not present..
        '''</summary>
        Friend Shared ReadOnly Property MissingExecutingArguments() As String
            Get
                Return ResourceManager.GetString("MissingExecutingArguments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The executing file extension entry is not present..
        '''</summary>
        Friend Shared ReadOnly Property MissingExecutingExtension() As String
            Get
                Return ResourceManager.GetString("MissingExecutingExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The executing file name entry is not present..
        '''</summary>
        Friend Shared ReadOnly Property MissingExecutingFileName() As String
            Get
                Return ResourceManager.GetString("MissingExecutingFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The executing folder name entry is not present..
        '''</summary>
        Friend Shared ReadOnly Property MissingExecutingFolder() As String
            Get
                Return ResourceManager.GetString("MissingExecutingFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file was not in the settings.  This is a required setting for the task to run..
        '''</summary>
        Friend Shared ReadOnly Property MissingFile() As String
            Get
                Return ResourceManager.GetString("MissingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The iis pages entry is not present..
        '''</summary>
        Friend Shared ReadOnly Property MissingIisPages() As String
            Get
                Return ResourceManager.GetString("MissingIisPages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The iis server entry is not present..
        '''</summary>
        Friend Shared ReadOnly Property MissingIisServerName() As String
            Get
                Return ResourceManager.GetString("MissingIisServerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The iis sites entry is not present..
        '''</summary>
        Friend Shared ReadOnly Property MissingIisSites() As String
            Get
                Return ResourceManager.GetString("MissingIisSites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The purge folder was not in the settings.  This is a required setting for the task to run..
        '''</summary>
        Friend Shared ReadOnly Property MissingPurgeFolder() As String
            Get
                Return ResourceManager.GetString("MissingPurgeFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The regular expression was not in the settings.  This is a required setting for the task to run..
        '''</summary>
        Friend Shared ReadOnly Property MissingRegularExpression() As String
            Get
                Return ResourceManager.GetString("MissingRegularExpression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The source folder was not in the settings.  This is a required setting for the task to run..
        '''</summary>
        Friend Shared ReadOnly Property MissingSourceFolder() As String
            Get
                Return ResourceManager.GetString("MissingSourceFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The source zip file was not in the settings.  This is a required setting for the task to run..
        '''</summary>
        Friend Shared ReadOnly Property MissingSourceZipFile() As String
            Get
                Return ResourceManager.GetString("MissingSourceZipFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opening Connection to Server.
        '''</summary>
        Friend Shared ReadOnly Property OpenServerConnection() As String
            Get
                Return ResourceManager.GetString("OpenServerConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanning file: {0} with regular expression {1}.
        '''</summary>
        Friend Shared ReadOnly Property ScanningFile() As String
            Get
                Return ResourceManager.GetString("ScanningFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The server name count does not equal the page count..
        '''</summary>
        Friend Shared ReadOnly Property ServerNamePagesCountsDifferent() As String
            Get
                Return ResourceManager.GetString("ServerNamePagesCountsDifferent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The server name count does not equal the site count..
        '''</summary>
        Friend Shared ReadOnly Property ServerNameSitesCountsDifferent() As String
            Get
                Return ResourceManager.GetString("ServerNameSitesCountsDifferent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specified file in configuration is found:.
        '''</summary>
        Friend Shared ReadOnly Property SpecifiedFileFound() As String
            Get
                Return ResourceManager.GetString("SpecifiedFileFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specified file in configuration is not found:.
        '''</summary>
        Friend Shared ReadOnly Property SpecifiedFileNotFound() As String
            Get
                Return ResourceManager.GetString("SpecifiedFileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specified folder in configuration is found:.
        '''</summary>
        Friend Shared ReadOnly Property SpecifiedFolderFound() As String
            Get
                Return ResourceManager.GetString("SpecifiedFolderFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specified folder in configuration is not found:.
        '''</summary>
        Friend Shared ReadOnly Property SpecifiedFolderNotFound() As String
            Get
                Return ResourceManager.GetString("SpecifiedFolderNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Standard Error:.
        '''</summary>
        Friend Shared ReadOnly Property StandardError() As String
            Get
                Return ResourceManager.GetString("StandardError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Standard Output:.
        '''</summary>
        Friend Shared ReadOnly Property StandardOutput() As String
            Get
                Return ResourceManager.GetString("StandardOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting backup.
        '''</summary>
        Friend Shared ReadOnly Property StartingBackup() As String
            Get
                Return ResourceManager.GetString("StartingBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to to .
        '''</summary>
        Friend Shared ReadOnly Property ToSpace() As String
            Get
                Return ResourceManager.GetString("ToSpace", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
